//! Bounded, bidirectional stdio RPC shared by aim and the plugin worker.

use std::collections::BTreeSet;
use std::path::PathBuf;

use aim_proto::content::Base64Bytes;
use aim_proto::ids::IdempotencyKey;
use aim_proto::tool::{ToolResult, ToolSpec};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::{PluginSource, SessionMetadata};

/// A single source, with component bytes encoded once as bounded base64.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct WireSource {
    /// Manifest text, at most 64 KiB.
    pub manifest_text: String,
    /// Component source bytes, at most 16 MiB.
    pub component: Base64Bytes,
    /// Whether source came from the workspace.
    pub project: bool,
}

impl From<PluginSource> for WireSource {
    fn from(source: PluginSource) -> Self {
        Self { manifest_text: source.manifest_text, component: Base64Bytes(source.component), project: source.project }
    }
}

impl From<WireSource> for PluginSource {
    fn from(source: WireSource) -> Self {
        Self { manifest_text: source.manifest_text, component: source.component.0, project: source.project }
    }
}

/// Initialize exactly one admitted plugin in a worker process.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct InitParams {
    /// One hash-pinned component and manifest.
    pub source: WireSource,
    /// Exact-hash grants intersected with the manifest by the worker.
    pub grants: BTreeSet<String>,
    /// Tool names admitted by the session's agent-narrowed host.
    pub allowed_tools: Vec<String>,
    /// Private owner home; the sandbox permits only its plugin KV/cache children.
    pub home: PathBuf,
    /// Read-only session facts.
    pub metadata: SessionMetadata,
}

/// Tool specs independently derived by the worker for admission comparison.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct InitResult {
    /// Namespaced model-facing tools.
    pub specs: Vec<ToolSpec>,
}

/// Call a plugin tool with an idempotency key prefixed by the active run identifier.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct CallParams {
    /// Namespaced tool name.
    pub name: String,
    /// JSON arguments.
    pub arguments: Value,
    /// Unique run identifier, generated by aim for callback validation.
    pub run_id: String,
    /// Outer idempotency key.
    pub key: IdempotencyKey,
}

/// Result of one plugin tool call.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct CallResult {
    /// Tool content and error state.
    pub result: ToolResult,
}

/// A nested tool call sent from the worker to aim.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct NestedCallParams {
    /// The active outer invocation.
    pub run_id: String,
    /// Tool to invoke through the agent-narrowed dispatcher.
    pub name: String,
    /// JSON arguments.
    pub arguments: Value,
    /// Run-prefixed idempotency key from the worker.
    pub key: IdempotencyKey,
}

/// Nested dispatcher result.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct NestedCallResult {
    /// Permissioned tool result.
    pub result: ToolResult,
}

/// One event for the guest's `on-event` export.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct EventParams {
    /// Event name.
    pub name: String,
    /// Event schema version.
    pub schema: u16,
    /// Monotonic event number.
    pub seq: u64,
    /// Owning session, if known.
    pub session: Option<String>,
    /// Event payload.
    pub payload: Value,
}

/// Empty success response for lifecycle operations.
#[derive(Clone, Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct Empty {}

aim_proto::method!(
    /// Initialize the admitted component without compiling it.
    Init = "plugin.init" (InitParams) -> InitResult
);
aim_proto::method!(
    /// Call one namespaced tool.
    CallTool = "plugin.call_tool" (CallParams) -> CallResult
);
aim_proto::method!(
    /// Deliver one event to the guest.
    OnEvent = "plugin.on_event" (EventParams) -> Empty
);
aim_proto::method!(
    /// End the active plugin instance.
    Shutdown = "plugin.shutdown" (Empty) -> Empty
);
aim_proto::method!(
    /// Re-enter aim's agent-narrowed tool dispatcher.
    NestedCall = "plugin.nested_call" (NestedCallParams) -> NestedCallResult
);
