//! Where the native loop's tool calls go (docs/architecture.md §6.3).
//!
//! A [`ToolHost`] offers tools and executes calls. The harness client (aimx over `aim-harness/1`)
//! is one host; the dispatcher that combines harness, agent, plugin and MCP tools is another.

use std::future::Future;
use std::pin::Pin;

use aim_proto::error::{ErrorCode, ProtoError};
use aim_proto::ids::IdempotencyKey;
use aim_proto::tool::{ToolContent, ToolResult, ToolSpec};
use serde_json::Value;

/// A boxed, sendable, owned future.
pub type BoxFuture<T> = Pin<Box<dyn Future<Output = T> + Send>>;

tokio::task_local! {
    static TOOL_CALL: ToolCallContext;
}

/// The model's tool call a tool host is running, while it runs (ADR 0066). The agent loop runs
/// each call future inside it, so a host whose call makes further calls (a code cell, a subagent)
/// can name its parent in session events and stop when the turn is cancelled. It crosses the
/// wrappers between the loop and a host because none of them spawns. `ToolHost::call` is unchanged.
#[derive(Clone, Debug)]
pub struct ToolCallContext {
    /// The provider's call id.
    pub call_id: String,
    /// The turn's session updates.
    pub events: tokio::sync::mpsc::UnboundedSender<aim_proto::daemon::SessionUpdate>,
    /// Cancelled when the turn is interrupted or its session closes.
    pub cancel: tokio_util::sync::CancellationToken,
}

impl ToolCallContext {
    /// The call being run by the current task, if any: `None` outside the agent loop.
    #[must_use]
    pub fn current() -> Option<Self> {
        TOOL_CALL.try_with(Clone::clone).ok()
    }

    /// Runs `future` as this call.
    pub fn scope<F: Future>(self, future: F) -> impl Future<Output = F::Output> {
        TOOL_CALL.scope(self, future)
    }

    /// Runs `start` (which creates a call's future) as this call.
    pub fn enter<R>(&self, start: impl FnOnce() -> R) -> R {
        TOOL_CALL.sync_scope(self.clone(), start)
    }
}

/// Most bytes from each end of a large Bash result shown to the model. aimx retains the complete
/// stream behind the result handle; only the transcript view is shortened (ADR 0056).
const BASH_MODEL_END_BYTES: usize = 5_500;
const BASH_MAX_END_BYTES: usize = 15_000;

fn bash_end_bytes() -> usize {
    std::env::var("AIM_BASH_MODEL_END_BYTES")
        .ok()
        .and_then(|value| value.parse::<usize>().ok())
        .filter(|bytes| (1..=BASH_MAX_END_BYTES).contains(bytes))
        .unwrap_or(BASH_MODEL_END_BYTES)
}

/// Bound a large shell result without losing its recovery handle or final status.
pub(crate) fn bound_bash_result(name: &str, mut result: ToolResult) -> ToolResult {
    let end_bytes = bash_end_bytes();
    if name != "Bash" || result.handle.is_none() {
        return result;
    }
    let handle = result.handle.as_ref().map_or("", aim_proto::ids::OutputHandle::as_str).to_owned();
    for part in &mut result.content {
        if let ToolContent::Text { text } = part
            && text.len() > 2 * end_bytes
        {
            let mut head = end_bytes;
            while !text.is_char_boundary(head) {
                head -= 1;
            }
            let mut tail = text.len() - end_bytes;
            while !text.is_char_boundary(tail) {
                tail += 1;
            }
            let omitted = tail - head;
            *text = format!(
                "{}\n… [{omitted} preview bytes omitted; read the full output with BashOutput({{\"id\":\"{handle}\"}}) or harness exec.read(proc={handle}, after_seq=0)] …\n{}",
                text.get(..head).unwrap_or_default(),
                text.get(tail..).unwrap_or_default()
            );
            result.truncated = true;
        }
    }
    result
}

/// Offers tools to the model and runs their calls.
pub trait ToolHost: Send + Sync {
    /// The tools, as advertised to the model.
    fn specs(&self) -> Vec<ToolSpec>;

    /// Runs one call. The future is owned (`'static`) so calls run concurrently with the loop;
    /// dropping it cancels the call. `key` is stable for a given call, so a retried call is
    /// deduplicated by the harness.
    ///
    /// A returned `Err` is a protocol-level failure (denied, unavailable, …); the loop shows it to
    /// the model as a failed tool result rather than aborting the turn.
    fn call(&self, name: String, arguments: Value, key: IdempotencyKey) -> BoxFuture<Result<ToolResult, ProtoError>>;

    /// Claims an absent destination through the harness before paying for generated content.
    fn reserve_blob(&self, _path: String, _key: IdempotencyKey) -> BoxFuture<Result<String, ProtoError>> {
        Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "workspace does not support file reservations")) })
    }

    /// Atomically replaces this session's reservation marker with generated bytes.
    fn finalize_blob(&self, _reservation: String, _bytes: Vec<u8>, _key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "workspace does not support file reservations")) })
    }

    /// Releases a reservation after generation fails or its output cannot be stored.
    fn cancel_blob(&self, _reservation: String, _key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "workspace does not support file reservations")) })
    }

    /// Writes generated binary content through the bound harness. The harness enforces workspace
    /// grants and idempotency, including when the workspace is on an SSH host.
    fn write_blob(&self, _path: String, _bytes: Vec<u8>, _key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "workspace does not support binary writes")) })
    }
}

/// Several tool hosts as one: specs are concatenated in order, and a name offered by an earlier
/// host shadows the same name later on (the workspace's tools always keep their names). Calls go
/// to the host that offered the name; binary writes go to the first host (the workspace).
pub struct Compose {
    hosts: Vec<std::sync::Arc<dyn ToolHost>>,
}

impl Compose {
    /// Composes `first` (the workspace, which keeps its names) with `rest`, in order.
    #[must_use]
    pub fn new(first: std::sync::Arc<dyn ToolHost>, rest: Vec<std::sync::Arc<dyn ToolHost>>) -> Self {
        let mut hosts = vec![first];
        hosts.extend(rest);
        Self { hosts }
    }

    fn owner(&self, name: &str) -> Option<&std::sync::Arc<dyn ToolHost>> {
        self.hosts.iter().find(|host| host.specs().iter().any(|spec| spec.name == name))
    }
}

impl ToolHost for Compose {
    fn specs(&self) -> Vec<ToolSpec> {
        let mut seen = std::collections::HashSet::new();
        self.hosts.iter().flat_map(|host| host.specs()).filter(|spec| seen.insert(spec.name.clone())).collect()
    }

    fn call(&self, name: String, arguments: Value, key: IdempotencyKey) -> BoxFuture<Result<ToolResult, ProtoError>> {
        match self.owner(&name) {
            Some(host) => host.call(name, arguments, key),
            None => Box::pin(async move { Err(ProtoError::new(ErrorCode::NotFound, format!("no tool named `{name}`"))) }),
        }
    }

    fn reserve_blob(&self, path: String, key: IdempotencyKey) -> BoxFuture<Result<String, ProtoError>> {
        match self.hosts.first() {
            Some(workspace) => workspace.reserve_blob(path, key),
            None => Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "no workspace")) }),
        }
    }

    fn finalize_blob(&self, reservation: String, bytes: Vec<u8>, key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        match self.hosts.first() {
            Some(workspace) => workspace.finalize_blob(reservation, bytes, key),
            None => Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "no workspace")) }),
        }
    }

    fn cancel_blob(&self, reservation: String, key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        match self.hosts.first() {
            Some(workspace) => workspace.cancel_blob(reservation, key),
            None => Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "no workspace")) }),
        }
    }

    fn write_blob(&self, path: String, bytes: Vec<u8>, key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        match self.hosts.first() {
            Some(workspace) => workspace.write_blob(path, bytes, key),
            None => Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "no workspace")) }),
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use super::*;
    use aim_proto::ids::OutputHandle;

    struct Named(&'static [&'static str], &'static str);

    impl ToolHost for Named {
        fn specs(&self) -> Vec<ToolSpec> {
            self.0
                .iter()
                .map(|name| ToolSpec {
                    name: (*name).to_owned(),
                    description: String::new(),
                    input_schema: serde_json::json!({"type": "object"}),
                    input: aim_proto::tool::ToolInput::default(),
                    annotations: aim_proto::tool::ToolAnnotations::default(),
                })
                .collect()
        }

        fn call(&self, _name: String, _arguments: Value, _key: IdempotencyKey) -> BoxFuture<Result<ToolResult, ProtoError>> {
            let from = self.1;
            Box::pin(async move { Ok(ToolResult::text(from)) })
        }
    }

    #[tokio::test]
    async fn earlier_hosts_keep_their_names_and_calls_route_to_the_owner() {
        let composed =
            Compose::new(Arc::new(Named(&["Read", "Bash"], "workspace")), vec![Arc::new(Named(&["Bash", "search_sessions"], "extra"))]);
        let names: Vec<String> = composed.specs().into_iter().map(|s| s.name).collect();
        assert_eq!(names, ["Read", "Bash", "search_sessions"], "a later Bash does not shadow the workspace's");
        let key = || IdempotencyKey::new("k".to_owned());
        assert_eq!(composed.call("Bash".into(), Value::Null, key()).await.unwrap(), ToolResult::text("workspace"));
        assert_eq!(composed.call("search_sessions".into(), Value::Null, key()).await.unwrap(), ToolResult::text("extra"));
        assert!(composed.call("nope".into(), Value::Null, key()).await.is_err());
    }

    #[test]
    fn shell_model_view_keeps_ends_and_recovery_handle() {
        let original = format!("START\n{}\nEND\n[full output is kept as handle h (BashOutput/exec.read)]", "x".repeat(30_000));
        let result = ToolResult { handle: Some(OutputHandle::new("h")), ..ToolResult::text(&original) };
        let bounded = bound_bash_result("Bash", result);
        let Some(ToolContent::Text { text }) = bounded.content.first() else {
            panic!("expected text");
        };
        assert!(text.starts_with("START"));
        assert!(text.ends_with("(BashOutput/exec.read)]"));
        assert!(text.contains("preview bytes omitted; read the full output with BashOutput({\"id\":\"h\"})"));
        assert!(text.len() < 12_000);
        assert_eq!(bounded.handle.as_ref().map(OutputHandle::as_str), Some("h"));
        assert!(bounded.truncated);
    }
}
