//! Where the native loop's tool calls go (docs/architecture.md §6.3).
//!
//! A [`ToolHost`] offers tools and executes calls. The harness client (aimx over `aim-harness/1`)
//! is one host; the dispatcher that combines harness, agent, plugin and MCP tools is another.

use std::future::Future;
use std::pin::Pin;

use aim_proto::error::{ErrorCode, ProtoError};
use aim_proto::ids::IdempotencyKey;
use aim_proto::tool::{ToolResult, ToolSpec};
use serde_json::Value;

/// A boxed, sendable, owned future.
pub type BoxFuture<T> = Pin<Box<dyn Future<Output = T> + Send>>;

/// Offers tools to the model and runs their calls.
pub trait ToolHost: Send + Sync {
    /// The tools, as advertised to the model.
    fn specs(&self) -> Vec<ToolSpec>;

    /// Runs one call. The future is owned (`'static`) so calls run concurrently with the loop;
    /// dropping it cancels the call. `key` is stable for a given call, so a retried call is
    /// deduplicated by the harness.
    ///
    /// A returned `Err` is a protocol-level failure (denied, unavailable, …); the loop shows it to
    /// the model as a failed tool result rather than aborting the turn.
    fn call(&self, name: String, arguments: Value, key: IdempotencyKey) -> BoxFuture<Result<ToolResult, ProtoError>>;

    /// Claims an absent destination through the harness before paying for generated content.
    fn reserve_blob(&self, _path: String, _key: IdempotencyKey) -> BoxFuture<Result<String, ProtoError>> {
        Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "workspace does not support file reservations")) })
    }

    /// Atomically replaces this session's reservation marker with generated bytes.
    fn finalize_blob(&self, _reservation: String, _bytes: Vec<u8>, _key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "workspace does not support file reservations")) })
    }

    /// Releases a reservation after generation fails or its output cannot be stored.
    fn cancel_blob(&self, _reservation: String, _key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "workspace does not support file reservations")) })
    }

    /// Writes generated binary content through the bound harness. The harness enforces workspace
    /// grants and idempotency, including when the workspace is on an SSH host.
    fn write_blob(&self, _path: String, _bytes: Vec<u8>, _key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "workspace does not support binary writes")) })
    }
}

/// Several tool hosts as one: specs are concatenated in order, and a name offered by an earlier
/// host shadows the same name later on (the workspace's tools always keep their names). Calls go
/// to the host that offered the name; binary writes go to the first host (the workspace).
pub struct Compose {
    hosts: Vec<std::sync::Arc<dyn ToolHost>>,
}

impl Compose {
    /// Composes `first` (the workspace, which keeps its names) with `rest`, in order.
    #[must_use]
    pub fn new(first: std::sync::Arc<dyn ToolHost>, rest: Vec<std::sync::Arc<dyn ToolHost>>) -> Self {
        let mut hosts = vec![first];
        hosts.extend(rest);
        Self { hosts }
    }

    fn owner(&self, name: &str) -> Option<&std::sync::Arc<dyn ToolHost>> {
        self.hosts.iter().find(|host| host.specs().iter().any(|spec| spec.name == name))
    }
}

impl ToolHost for Compose {
    fn specs(&self) -> Vec<ToolSpec> {
        let mut seen = std::collections::HashSet::new();
        self.hosts.iter().flat_map(|host| host.specs()).filter(|spec| seen.insert(spec.name.clone())).collect()
    }

    fn call(&self, name: String, arguments: Value, key: IdempotencyKey) -> BoxFuture<Result<ToolResult, ProtoError>> {
        match self.owner(&name) {
            Some(host) => host.call(name, arguments, key),
            None => Box::pin(async move { Err(ProtoError::new(ErrorCode::NotFound, format!("no tool named `{name}`"))) }),
        }
    }

    fn reserve_blob(&self, path: String, key: IdempotencyKey) -> BoxFuture<Result<String, ProtoError>> {
        match self.hosts.first() {
            Some(workspace) => workspace.reserve_blob(path, key),
            None => Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "no workspace")) }),
        }
    }

    fn finalize_blob(&self, reservation: String, bytes: Vec<u8>, key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        match self.hosts.first() {
            Some(workspace) => workspace.finalize_blob(reservation, bytes, key),
            None => Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "no workspace")) }),
        }
    }

    fn cancel_blob(&self, reservation: String, key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        match self.hosts.first() {
            Some(workspace) => workspace.cancel_blob(reservation, key),
            None => Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "no workspace")) }),
        }
    }

    fn write_blob(&self, path: String, bytes: Vec<u8>, key: IdempotencyKey) -> BoxFuture<Result<(), ProtoError>> {
        match self.hosts.first() {
            Some(workspace) => workspace.write_blob(path, bytes, key),
            None => Box::pin(async { Err(ProtoError::new(ErrorCode::Unavailable, "no workspace")) }),
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use super::*;

    struct Named(&'static [&'static str], &'static str);

    impl ToolHost for Named {
        fn specs(&self) -> Vec<ToolSpec> {
            self.0
                .iter()
                .map(|name| ToolSpec {
                    name: (*name).to_owned(),
                    description: String::new(),
                    input_schema: serde_json::json!({"type": "object"}),
                    input: aim_proto::tool::ToolInput::default(),
                    annotations: aim_proto::tool::ToolAnnotations::default(),
                })
                .collect()
        }

        fn call(&self, _name: String, _arguments: Value, _key: IdempotencyKey) -> BoxFuture<Result<ToolResult, ProtoError>> {
            let from = self.1;
            Box::pin(async move { Ok(ToolResult::text(from)) })
        }
    }

    #[tokio::test]
    async fn earlier_hosts_keep_their_names_and_calls_route_to_the_owner() {
        let composed =
            Compose::new(Arc::new(Named(&["Read", "Bash"], "workspace")), vec![Arc::new(Named(&["Bash", "search_sessions"], "extra"))]);
        let names: Vec<String> = composed.specs().into_iter().map(|s| s.name).collect();
        assert_eq!(names, ["Read", "Bash", "search_sessions"], "a later Bash does not shadow the workspace's");
        let key = || IdempotencyKey::new("k".to_owned());
        assert_eq!(composed.call("Bash".into(), Value::Null, key()).await.unwrap(), ToolResult::text("workspace"));
        assert_eq!(composed.call("search_sessions".into(), Value::Null, key()).await.unwrap(), ToolResult::text("extra"));
        assert!(composed.call("nope".into(), Value::Null, key()).await.is_err());
    }
}
